INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:root:Get customer request successful
INFO:werkzeug:127.0.0.1 - - [01/Oct/2023 19:13:48] "GET /api/get/customer HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:root:Get customer request successful
INFO:werkzeug:127.0.0.1 - - [01/Oct/2023 20:58:57] "GET /api/get/customer HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [01/Oct/2023 20:59:03] "[33mGET /api/get/customer HTTP/1.1[0m" 404 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [02/Oct/2023 20:45:23] "[31m[1mGET /add/product/feedback HTTP/1.1[0m" 405 -
ERROR:app:Exception on /add/product/feedback [POST]
Traceback (most recent call last):
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\Documents\Projects\Python\CRM\api_routes_feedback.py", line 40, in add_brand_feedback
    productFeedback = ProductFeedback(custmer_id=data['customerid'],
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 4, in __init__
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\state.py", line 575, in _initialize_instance
    with util.safe_reraise():
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\state.py", line 573, in _initialize_instance
    manager.original_init(*mixed[1:], **kwargs)
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\decl_base.py", line 2073, in _declarative_constructor
    raise TypeError(
TypeError: 'custmer_id' is an invalid keyword argument for ProductFeedback
INFO:werkzeug:127.0.0.1 - - [02/Oct/2023 20:45:32] "[35m[1mPOST /add/product/feedback HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:root:Product feedback added
INFO:werkzeug:127.0.0.1 - - [02/Oct/2023 20:46:44] "POST /add/product/feedback HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [02/Oct/2023 20:51:09] "[33mPOST /add/brandt/feedback HTTP/1.1[0m" 404 -
INFO:root:Feedback saved
INFO:werkzeug:127.0.0.1 - - [02/Oct/2023 20:51:19] "POST /add/brand/feedback HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
ERROR:app:Exception on /api/get/customer [GET]
Traceback (most recent call last):
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\Documents\Projects\Python\CRM\api_routes_customer.py", line 18, in api_get_customer
    turnover += product.price
    ^^^^^^^^
UnboundLocalError: cannot access local variable 'turnover' where it is not associated with a value
INFO:werkzeug:127.0.0.1 - - [05/Oct/2023 19:05:26] "[35m[1mGET /api/get/customer HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:root:Get customer request successful
INFO:werkzeug:127.0.0.1 - - [05/Oct/2023 19:06:19] "GET /api/get/customer HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:root:Get customer request successful
INFO:werkzeug:127.0.0.1 - - [05/Oct/2023 19:07:46] "GET /api/get/customer HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [06/Oct/2023 20:37:43] "[33mPOST /api/add/customer/request HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2023 20:37:57] "[33mPOST /api/open/customer/request HTTP/1.1[0m" 404 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:root:Customer request has been registered
INFO:werkzeug:127.0.0.1 - - [06/Oct/2023 20:38:55] "POST /api/open/customer/request HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2023 20:39:08] "[31m[1mPOST /api/open/customer/request HTTP/1.1[0m" 400 -
ERROR:root:Wrong query parameters
INFO:werkzeug:127.0.0.1 - - [06/Oct/2023 20:41:47] "[31m[1mPOST /api/open/customer/request HTTP/1.1[0m" 400 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
ERROR:app:Exception on /api/close/customer/request [POST]
Traceback (most recent call last):
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\base.py", line 1808, in _execute_context
    context = constructor(
              ^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\default.py", line 1261, in _init_compiled
    l_param: List[Any] = [
                         ^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\default.py", line 1262, in <listcomp>
    flattened_processors[key](compiled_params[key])
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\sql\sqltypes.py", line 1994, in process
    value = _strict_as_bool(value)
            ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\sql\sqltypes.py", line 1966, in _strict_as_bool
    raise TypeError("Not a boolean value: %r" % (value,))
TypeError: Not a boolean value: 'true'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\Documents\Projects\Python\CRM\api_routes_customer_requests.py", line 31, in api_close_customer_request
    db.session.commit()
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\scoping.py", line 538, in commit
    return self._proxied.commit()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\session.py", line 1903, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 137, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\session.py", line 1218, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 137, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\session.py", line 1193, in _prepare_impl
    self.session.flush()
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\session.py", line 4153, in flush
    self._flush(objects)
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\session.py", line 4289, in _flush
    with util.safe_reraise():
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\session.py", line 4250, in _flush
    flush_context.execute()
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 467, in execute
    rec.execute(self)
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 644, in execute
    util.preloaded.orm_persistence.save_obj(
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\persistence.py", line 85, in save_obj
    _emit_update_statements(
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\persistence.py", line 894, in _emit_update_statements
    c = connection.execute(
        ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\base.py", line 1414, in execute
    return meth(
           ^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\sql\elements.py", line 485, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\base.py", line 1814, in _execute_context
    self._handle_dbapi_exception(
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\base.py", line 2325, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\base.py", line 1808, in _execute_context
    context = constructor(
              ^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\default.py", line 1261, in _init_compiled
    l_param: List[Any] = [
                         ^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\default.py", line 1262, in <listcomp>
    flattened_processors[key](compiled_params[key])
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\sql\sqltypes.py", line 1994, in process
    value = _strict_as_bool(value)
            ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\sql\sqltypes.py", line 1966, in _strict_as_bool
    raise TypeError("Not a boolean value: %r" % (value,))
sqlalchemy.exc.StatementError: (builtins.TypeError) Not a boolean value: 'true'
[SQL: UPDATE customer_request SET resolved=?, resolution=?, resolution_date=? WHERE customer_request.id = ?]
[parameters: [{'resolved': 'true', 'resolution_date': datetime.datetime(2023, 10, 6, 20, 45, 5, 406305), 'resolution': 'Booked an oil change appointment for 11.10.2023 @ 11:30 at our service center', 'customer_request_id': 1}]]
INFO:werkzeug:127.0.0.1 - - [06/Oct/2023 20:45:05] "[35m[1mPOST /api/close/customer/request HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:root:resolution ticket has been updated
INFO:werkzeug:127.0.0.1 - - [06/Oct/2023 20:45:29] "POST /api/close/customer/request HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2023 20:45:42] "[31m[1mPOST /api/close/customer/request HTTP/1.1[0m" 400 -
ERROR:root:Wrong query parameters
INFO:werkzeug:127.0.0.1 - - [06/Oct/2023 20:45:47] "[31m[1mPOST /api/close/customer/request HTTP/1.1[0m" 400 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
ERROR:app:Exception on /api/get/customer/request [GET]
Traceback (most recent call last):
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\Documents\Projects\Python\CRM\api_routes_customer_requests.py", line 47, in api_get_customer_request
    crr = CustomerRequestResponse(customerRequest)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\Documents\Projects\Python\CRM\customer_response.py", line 40, in __init__
    self.request_date = customerRequest.requestDate
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'CustomerRequest' object has no attribute 'requestDate'
INFO:werkzeug:127.0.0.1 - - [06/Oct/2023 20:55:45] "[35m[1mGET /api/get/customer/request HTTP/1.1[0m" 500 -
ERROR:app:Exception on /api/get/customer/request [GET]
Traceback (most recent call last):
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\Documents\Projects\Python\CRM\api_routes_customer_requests.py", line 47, in api_get_customer_request
    crr = CustomerRequestResponse(customerRequest)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\Documents\Projects\Python\CRM\customer_response.py", line 40, in __init__
    self.request_date = customerRequest.requestDate
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'CustomerRequest' object has no attribute 'requestDate'
INFO:werkzeug:127.0.0.1 - - [06/Oct/2023 20:55:58] "[35m[1mGET /api/get/customer/request HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:root:CustomerRequest fetched
INFO:werkzeug:127.0.0.1 - - [06/Oct/2023 21:00:23] "GET /api/get/customer/request HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [07/Oct/2023 09:48:35] "[33mGET /api/get/customer/feedback HTTP/1.1[0m" 404 -
ERROR:root:Wrong query parameters
INFO:werkzeug:127.0.0.1 - - [07/Oct/2023 09:48:53] "[31m[1mGET /api/get/product/feedback HTTP/1.1[0m" 400 -
INFO:root:Brand feedback records retrieved
ERROR:app:Exception on /api/get/product/feedback [GET]
Traceback (most recent call last):
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1826, in full_dispatch_request
    return self.finalize_request(rv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1845, in finalize_request
    response = self.make_response(rv)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2156, in make_response
    rv = self.json.response(rv)
         ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\json\provider.py", line 309, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=mimetype
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\json\provider.py", line 230, in dumps
    return json.dumps(obj, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\json\provider.py", line 122, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type method is not JSON serializable
INFO:werkzeug:127.0.0.1 - - [07/Oct/2023 09:49:04] "[35m[1mGET /api/get/product/feedback HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:root:Brand feedback records retrieved
ERROR:app:Exception on /api/get/product/feedback [GET]
Traceback (most recent call last):
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1826, in full_dispatch_request
    return self.finalize_request(rv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1845, in finalize_request
    response = self.make_response(rv)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2156, in make_response
    rv = self.json.response(rv)
         ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\json\provider.py", line 309, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=mimetype
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\json\provider.py", line 230, in dumps
    return json.dumps(obj, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\json\provider.py", line 122, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type method is not JSON serializable
INFO:werkzeug:127.0.0.1 - - [07/Oct/2023 09:51:53] "[35m[1mGET /api/get/product/feedback HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:root:Brand feedback records retrieved
ERROR:app:Exception on /api/get/product/feedback [GET]
Traceback (most recent call last):
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1826, in full_dispatch_request
    return self.finalize_request(rv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1845, in finalize_request
    response = self.make_response(rv)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2156, in make_response
    rv = self.json.response(rv)
         ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\json\provider.py", line 309, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=mimetype
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\json\provider.py", line 230, in dumps
    return json.dumps(obj, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\json\provider.py", line 122, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type method is not JSON serializable
INFO:werkzeug:127.0.0.1 - - [07/Oct/2023 09:53:40] "[35m[1mGET /api/get/product/feedback HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:root:Brand feedback records retrieved
INFO:werkzeug:127.0.0.1 - - [07/Oct/2023 09:54:26] "GET /api/get/product/feedback HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:root:Brand feedback records retrieved
INFO:werkzeug:127.0.0.1 - - [07/Oct/2023 09:55:13] "GET /api/get/brand/feedback HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:root:Stoyan Todorov with c.todopob@gmail.com initiated export of customer data
ERROR:app:Exception on /api/customer/export [GET]
Traceback (most recent call last):
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\Documents\Projects\Python\CRM\api_routes_customer.py", line 159, in api_customer_export
    workbook.save(f'/uploaded/{excel_file}')
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\openpyxl\workbook\workbook.py", line 386, in save
    save_workbook(self, filename)
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\openpyxl\writer\excel.py", line 291, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\zipfile.py", line 1281, in __init__
    self.fp = io.open(file, filemode)
              ^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/uploaded/customers_data19102023_1922.xlsx'
INFO:werkzeug:127.0.0.1 - - [19/Oct/2023 19:22:57] "[35m[1mGET /api/customer/export HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:root:Stoyan Todorov with c.todopob@gmail.com initiated export of customer data
INFO:root:Export successful
ERROR:app:Exception on /api/customer/export [GET]
Traceback (most recent call last):
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\Documents\Projects\Python\CRM\api_routes_customer.py", line 161, in api_customer_export
    return send_from_directory(directory=app.config['UPLOAD_FOLDER'] ,filename=excel_file)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: send_from_directory() missing 1 required positional argument: 'path'
INFO:werkzeug:127.0.0.1 - - [19/Oct/2023 19:24:07] "[35m[1mGET /api/customer/export HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:root:Stoyan Todorov with c.todopob@gmail.com initiated export of customer data
INFO:root:Export successful
INFO:werkzeug:127.0.0.1 - - [19/Oct/2023 21:20:29] "GET /api/customer/export HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:root:stoyan todorov with c.todopob@gmail.com initiated export of customer data
ERROR:app:Exception on /api/product/export [GET]
Traceback (most recent call last):
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\Documents\Projects\Python\CRM\api_routes_product.py", line 146, in api_product_export
    worksheet[f'G{row}'] = product.review
    ~~~~~~~~~^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\openpyxl\worksheet\worksheet.py", line 318, in __setitem__
    self[key].value = value
    ^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\openpyxl\cell\cell.py", line 218, in value
    self._bind_value(value)
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\openpyxl\cell\cell.py", line 187, in _bind_value
    raise ValueError("Cannot convert {0!r} to Excel".format(value))
ValueError: Cannot convert [<ProductFeedback 1>] to Excel
INFO:werkzeug:127.0.0.1 - - [23/Oct/2023 20:33:51] "[35m[1mGET /api/product/export HTTP/1.1[0m" 500 -
INFO:root:stoyan todorov with c.todopob@gmail.com initiated export of customer data
ERROR:app:Exception on /api/product/export [GET]
Traceback (most recent call last):
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\Documents\Projects\Python\CRM\api_routes_product.py", line 146, in api_product_export
    row += 1
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\openpyxl\worksheet\worksheet.py", line 318, in __setitem__
    self[key].value = value
    ^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\openpyxl\cell\cell.py", line 218, in value
    self._bind_value(value)
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\openpyxl\cell\cell.py", line 187, in _bind_value
    raise ValueError("Cannot convert {0!r} to Excel".format(value))
ValueError: Cannot convert [<ProductFeedback 1>] to Excel
INFO:werkzeug:127.0.0.1 - - [23/Oct/2023 20:36:41] "[35m[1mGET /api/product/export HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:root:stoyan todorov with c.todopob@gmail.com initiated export of customer data
ERROR:app:Exception on /api/product/export [GET]
Traceback (most recent call last):
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\Documents\Projects\Python\CRM\api_routes_product.py", line 149, in api_product_export
    workbook.save(f'/uploaded/{excel_file}')
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\openpyxl\workbook\workbook.py", line 386, in save
    save_workbook(self, filename)
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\openpyxl\writer\excel.py", line 291, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\zipfile.py", line 1281, in __init__
    self.fp = io.open(file, filemode)
              ^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/uploaded/customers_data23102023_2041.xlsx'
INFO:werkzeug:127.0.0.1 - - [23/Oct/2023 20:41:42] "[35m[1mGET /api/product/export HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:root:stoyan todorov with c.todopob@gmail.com initiated export of customer data
INFO:root:Export successful
INFO:werkzeug:127.0.0.1 - - [23/Oct/2023 20:42:46] "GET /api/product/export HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [24/Oct/2023 20:31:41] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [24/Oct/2023 20:31:41] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [24/Oct/2023 20:35:42] "GET / HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [24/Oct/2023 23:48:45] "GET / HTTP/1.1" 200 -
ERROR:app:Exception on /upload/customers [POST]
Traceback (most recent call last):
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\Documents\Projects\Python\CRM\app.py", line 158, in import_customers
    flash('No or corrupted file')
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\helpers.py", line 361, in flash
    session["_flashes"] = flashes
    ~~~~~~~^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\sessions.py", line 98, in _fail
    raise RuntimeError(
RuntimeError: The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.
INFO:werkzeug:127.0.0.1 - - [24/Oct/2023 23:49:00] "[35m[1mPOST /upload/customers HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
ERROR:app:Exception on /upload/customers [POST]
Traceback (most recent call last):
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\Documents\Projects\Python\CRM\app.py", line 158, in import_customers
    flash('No or corrupted file')
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\helpers.py", line 361, in flash
    session["_flashes"] = flashes
    ~~~~~~~^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\sessions.py", line 98, in _fail
    raise RuntimeError(
RuntimeError: The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.
INFO:werkzeug:127.0.0.1 - - [24/Oct/2023 23:50:56] "[35m[1mPOST /upload/customers HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
ERROR:app:Exception on /upload/customers [POST]
Traceback (most recent call last):
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\Documents\Projects\Python\CRM\app.py", line 158, in import_customers
    flash('No or corrupted file')
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\helpers.py", line 361, in flash
    session["_flashes"] = flashes
    ~~~~~~~^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\sessions.py", line 98, in _fail
    raise RuntimeError(
RuntimeError: The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.
INFO:werkzeug:127.0.0.1 - - [24/Oct/2023 23:52:09] "[35m[1mPOST /upload/customers HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [24/Oct/2023 23:54:11] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [24/Oct/2023 23:54:18] "[32mPOST /upload/customers HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [24/Oct/2023 23:54:18] "GET / HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [24/Oct/2023 23:56:33] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [24/Oct/2023 23:56:41] "[32mPOST /upload/customers HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [24/Oct/2023 23:56:41] "GET / HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [24/Oct/2023 23:58:09] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [24/Oct/2023 23:58:16] "[32mPOST /upload/customers HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [24/Oct/2023 23:58:16] "GET / HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [24/Oct/2023 23:58:55] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [24/Oct/2023 23:59:01] "[32mPOST /upload/customers HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [24/Oct/2023 23:59:01] "GET / HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [24/Oct/2023 23:59:32] "GET / HTTP/1.1" 200 -
ERROR:app:Exception on /upload/customers [POST]
Traceback (most recent call last):
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\Documents\Projects\Python\CRM\app.py", line 158, in import_customers
    flash(f'No or corrupted file {file}')
                                  ^^^^
UnboundLocalError: cannot access local variable 'file' where it is not associated with a value
INFO:werkzeug:127.0.0.1 - - [24/Oct/2023 23:59:38] "[35m[1mPOST /upload/customers HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [25/Oct/2023 00:01:52] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [25/Oct/2023 00:01:58] "[32mPOST /upload/customers HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [25/Oct/2023 00:01:58] "GET / HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [25/Oct/2023 00:03:03] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [25/Oct/2023 00:03:10] "[32mPOST /upload/customers HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [25/Oct/2023 00:03:10] "GET / HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [25/Oct/2023 00:04:13] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [25/Oct/2023 00:04:19] "[31m[1mPOST /upload/customers HTTP/1.1[0m" 400 -
INFO:werkzeug:127.0.0.1 - - [25/Oct/2023 00:04:53] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [25/Oct/2023 00:05:01] "[31m[1mPOST /upload/customers HTTP/1.1[0m" 400 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [25/Oct/2023 00:08:09] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [25/Oct/2023 00:08:15] "[31m[1mPOST /upload/customers HTTP/1.1[0m" 400 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [25/Oct/2023 00:09:27] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [25/Oct/2023 00:09:33] "[32mPOST /upload/customers HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [25/Oct/2023 00:09:33] "GET / HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [25/Oct/2023 00:12:49] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [25/Oct/2023 00:12:56] "[32mPOST /upload/customers HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [25/Oct/2023 00:12:56] "GET / HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [25/Oct/2023 00:15:42] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [25/Oct/2023 00:15:47] "[32mPOST /upload/customers HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [25/Oct/2023 00:15:47] "GET / HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [25/Oct/2023 00:20:44] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [25/Oct/2023 00:20:49] "[32mPOST /upload/customers HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [25/Oct/2023 00:20:49] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [25/Oct/2023 00:24:30] "[32mPOST /upload/customers HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [25/Oct/2023 00:24:30] "GET / HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [25/Oct/2023 00:36:21] "GET / HTTP/1.1" 200 -
ERROR:app:Exception on /upload/customers [POST]
Traceback (most recent call last):
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\Documents\Projects\Python\CRM\app.py", line 158, in import_customers
    print(request.form.get['custfile'])
          ~~~~~~~~~~~~~~~~^^^^^^^^^^^^
TypeError: 'method' object is not subscriptable
INFO:werkzeug:127.0.0.1 - - [25/Oct/2023 00:36:27] "[35m[1mPOST /upload/customers HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [25/Oct/2023 00:37:22] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [25/Oct/2023 00:37:27] "[32mPOST /upload/customers HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [25/Oct/2023 00:37:28] "GET / HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [25/Oct/2023 00:39:03] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [25/Oct/2023 00:39:12] "[32mPOST /upload/customers HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [25/Oct/2023 00:39:12] "GET / HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [25/Oct/2023 00:41:30] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [25/Oct/2023 00:41:36] "[32mPOST /upload/customers HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [25/Oct/2023 00:41:36] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [25/Oct/2023 00:46:08] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [25/Oct/2023 00:46:13] "[32mPOST /upload/customers HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [25/Oct/2023 00:46:13] "GET / HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [25/Oct/2023 00:47:45] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [25/Oct/2023 00:47:50] "[32mPOST /upload/customers HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [25/Oct/2023 00:47:50] "GET / HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [25/Oct/2023 00:48:45] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [25/Oct/2023 00:48:51] "[32mPOST /upload/customers HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [25/Oct/2023 00:48:51] "GET / HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [25/Oct/2023 00:50:28] "[32mPOST /upload/customers HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [25/Oct/2023 00:50:28] "GET / HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [25/Oct/2023 00:51:16] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [25/Oct/2023 00:51:22] "[32mPOST /upload/customers HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [25/Oct/2023 00:51:22] "GET / HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [25/Oct/2023 00:52:48] "GET / HTTP/1.1" 200 -
ERROR:app:Exception on /upload/customers [POST]
Traceback (most recent call last):
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\Documents\Projects\Python\CRM\app.py", line 172, in import_customers
    db_upload_customers(filepath)
  File "C:\Users\ctodo\Documents\Projects\Python\CRM\app.py", line 41, in db_upload_customers
    for row in worksheet.iter_rows():
               ^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'iter_rows'
INFO:werkzeug:127.0.0.1 - - [25/Oct/2023 00:52:53] "[35m[1mPOST /upload/customers HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [25/Oct/2023 00:54:51] "GET / HTTP/1.1" 200 -
ERROR:app:Exception on /upload/customers [POST]
Traceback (most recent call last):
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\Documents\Projects\Python\CRM\app.py", line 172, in import_customers
    db_upload_customers(filepath)
  File "C:\Users\ctodo\Documents\Projects\Python\CRM\app.py", line 41, in db_upload_customers
    for row in worksheet.iter_rows():
               ^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'iter_rows'
INFO:werkzeug:127.0.0.1 - - [25/Oct/2023 00:54:58] "[35m[1mPOST /upload/customers HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [25/Oct/2023 00:57:19] "GET / HTTP/1.1" 200 -
ERROR:app:Exception on /upload/customers [POST]
Traceback (most recent call last):
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\Documents\Projects\Python\CRM\app.py", line 173, in import_customers
    db_upload_customers(filepath)
  File "C:\Users\ctodo\Documents\Projects\Python\CRM\app.py", line 50, in db_upload_customers
    opt_email=strToBool(row[4]),
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\Documents\Projects\Python\CRM\utils.py", line 2, in strToBool
    if value.lower() == "false" or "":
       ^^^^^^^^^^^
AttributeError: 'Cell' object has no attribute 'lower'
INFO:werkzeug:127.0.0.1 - - [25/Oct/2023 00:57:24] "[35m[1mPOST /upload/customers HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [25/Oct/2023 01:00:01] "GET / HTTP/1.1" 200 -
ERROR:app:Exception on /upload/customers [POST]
Traceback (most recent call last):
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\Documents\Projects\Python\CRM\app.py", line 172, in import_customers
    db_upload_customers(filepath)
  File "C:\Users\ctodo\Documents\Projects\Python\CRM\app.py", line 49, in db_upload_customers
    opt_email=strToBool(row[4].value),
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\Documents\Projects\Python\CRM\utils.py", line 2, in strToBool
    if value.lower() == "false" or "":
       ^^^^^^^^^^^
AttributeError: 'bool' object has no attribute 'lower'
INFO:werkzeug:127.0.0.1 - - [25/Oct/2023 01:00:07] "[35m[1mPOST /upload/customers HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [25/Oct/2023 01:02:11] "GET / HTTP/1.1" 200 -
ERROR:app:Exception on /upload/customers [POST]
Traceback (most recent call last):
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\base.py", line 1808, in _execute_context
    context = constructor(
              ^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\default.py", line 1261, in _init_compiled
    l_param: List[Any] = [
                         ^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\default.py", line 1262, in <listcomp>
    flattened_processors[key](compiled_params[key])
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\dialects\sqlite\base.py", line 1081, in process
    raise TypeError(
TypeError: SQLite DateTime type only accepts Python datetime and date objects as input.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\Documents\Projects\Python\CRM\app.py", line 172, in import_customers
    db_upload_customers(filepath)
  File "C:\Users\ctodo\Documents\Projects\Python\CRM\app.py", line 56, in db_upload_customers
    db.session.commit()
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\scoping.py", line 538, in commit
    return self._proxied.commit()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\session.py", line 1903, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 137, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\session.py", line 1218, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 137, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\session.py", line 1193, in _prepare_impl
    self.session.flush()
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\session.py", line 4153, in flush
    self._flush(objects)
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\session.py", line 4289, in _flush
    with util.safe_reraise():
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\session.py", line 4250, in _flush
    flush_context.execute()
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 467, in execute
    rec.execute(self)
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 644, in execute
    util.preloaded.orm_persistence.save_obj(
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\persistence.py", line 1188, in _emit_insert_statements
    result = connection.execute(
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\base.py", line 1414, in execute
    return meth(
           ^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\sql\elements.py", line 485, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\base.py", line 1814, in _execute_context
    self._handle_dbapi_exception(
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\base.py", line 2325, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\base.py", line 1808, in _execute_context
    context = constructor(
              ^^^^^^^^^^^^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\default.py", line 1261, in _init_compiled
    l_param: List[Any] = [
                         ^
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\default.py", line 1262, in <listcomp>
    flattened_processors[key](compiled_params[key])
  File "C:\Users\ctodo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\dialects\sqlite\base.py", line 1081, in process
    raise TypeError(
sqlalchemy.exc.StatementError: (builtins.TypeError) SQLite DateTime type only accepts Python datetime and date objects as input.
[SQL: INSERT INTO customer (name, email, address, phone, opt_email, opt_phone, opt_chat, status, revenue, last_updated, last_contacted) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: [{'name': 'Vasil Dimitrov', 'email': 'vasil.d.dimitrov@vivacom.bg', 'status': 'active', 'opt_chat': False, 'address': '1 Stara Planina str. Burgas 8000 Bulgaria', 'opt_phone': False, 'phone': '0878560312', 'opt_email': True, 'last_contacted': None}]]
INFO:werkzeug:127.0.0.1 - - [25/Oct/2023 01:02:17] "[35m[1mPOST /upload/customers HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [25/Oct/2023 01:05:19] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [25/Oct/2023 01:05:24] "[32mPOST /upload/customers HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [25/Oct/2023 01:05:24] "GET / HTTP/1.1" 200 -
